### ISSUE TITLE
pretrained kitti weight

### ISSUE THREAD

**Issue by xiaomaicha** [packyan/PyTorch-YOLOv3-kitti#1]
Download pretrained weights please download weights/yolov3-kitti.weights
**Thank you for your code repository. I saw the trained weight of the Kitti in your readme to be download. Where can I download it?**

**Comment by packyan** [comment]
Here it is.
https://drive.google.com/file/d/1BRJDDCMRXdQdQs6-x-3PmlzcEuT9wxJV/view?usp=sharing

**Comment by Aldo-Aditiya** [comment]
Hi, I know this is a 2 year old repo... but I would like to ask you - did you make the pretrained weights using all of the kitti dataset, or just the images that you provide with the repo?

**Comment by packyan** [comment]
> Hi, I know this is a 2 year old repo... but I would like to ask you - did you make the pretrained weights using all of the kitti dataset, or just the images that you provide with the repo?

All images of kitti.

**Comment by Aldo-Aditiya** [comment]
thank you 👍
