### ISSUE TITLE
train/val split used to obtain yolov3-kitti.weights

### ISSUE THREAD

**Issue by vipinpillai** [packyan/PyTorch-YOLOv3-kitti#5]
Thanks for sharing your work. 
Could you please clarify the train/val split that was used to train the model corresponding to the yolov3-kitti.weights?
Is it the standard 3717 / 3769 split or was all of the 7481 images used for training?

**Comment by priteshgohil** [comment]
Waiting for the author's response.

**Comment by packyan** [comment]
Sorry, this repo is just a course design, I almost forgot these implement detials. I guess you guys have been sloved this problem already...

**Comment by packyan** [comment]
Sorry, this repo is just a course design, I almost forgot these implement detials. I guess you guys have been sloved this problem already...

**Comment by packyan** [comment]
If I was not wrong, the pretrained weights may trained by all data. But I'm not sure, sorry.
