### ISSUE TITLE
pretrained kitti weight epoch?

### ISSUE THREAD

**Issue by priteshgohil** [packyan/PyTorch-YOLOv3-kitti#7]
Hi Packyan,
Thanks for the code. When was the weights are saved? Is it at default 100 epoch or some other?

**Comment by packyan** [comment]
if epoch % opt.checkpoint_interval == 0:
        model.save_weights("%s/%d.weights" % (opt.checkpoint_dir, epoch))
it depends on opt.checkpoint_interval. This repo is just a course design, so I will not update it or fix bugs, sorry.
